### ISSUE TITLE
SystemSovereignty only contains faction_id

### ISSUE THREAD

**Issue by BitBaboonSteve** [seraphx2/ESI.NET#14]
The ESI.NET.Models.Sovereignty.SystemSovereignty only contains the faction_id; yet this can return both a corp corporation_id and an alliance id.

**Comment by DanFraserUK** [comment]
From the /sovereignty/map/ endpoint?

Proposed fix:
`public class SystemSovereignty
 {
        [JsonProperty("alliance_id")]
        public int AllianceId { get; set; }

	[JsonProperty("corporation_id")]
	public int CorporationId { get; set; }

	[JsonProperty("faction_id")]
	public int FactionId { get; set; }

	[JsonProperty("system_id")]
	public int SystemId { get; set; }
}`

Temporary fix for users of ESI.NET:
`public class SystemSovereigntyTemp : SystemSovereignty
{
        [JsonProperty("alliance_id")]
        public int AllianceId { get; set; }

	[JsonProperty("corporation_id")]
	public int CorporationId { get; set; }
}`
