### ISSUE TITLE
Page logic

### ISSUE THREAD

**Issue by mrurb** [seraphx2/ESI.NET#16]
There seem to be a distinct lack of page logic for the requests supporting paging. EX: https://github.com/seraphx2/ESI.NET/blob/695c449a0e432c068eb8617b15bb4f34b310d6ac/ESI.NET/Logic/WalletLogic.cs#L99 should have an extra parameter for what page to choose

**Comment by seraphx2** [comment]
Previously, journal entries were retrieved by a "from_id" value and would return a set amount of records in the past from that id. This is how CCP chose to do this before they had implemented paging properly. After reviewing the swagger spec, I see they have replaced `from_id` with `page`.
