### ISSUE TITLE
RefId returns 0 from JournalEntry

### ISSUE THREAD

**Issue by mrurb** [seraphx2/ESI.NET#17]
RefId seems to return 0, from what i can see the model uses a long, but the documentation says it should be an int64. Not sure if this is the problem, but all RefId returns 0 for me.
![image](https://user-images.githubusercontent.com/3414748/53045384-c57f5400-348d-11e9-8b70-26e3aa3a1ffa.png)

**Comment by seraphx2** [comment]
int is an alias for Int32. long is an alias for In64.
So that should not be the problem.
i will look into it and see what's going on.

**Comment by seraphx2** [comment]
Oh, it looks like you are still using an old version of the API. I upgraded a few days ago to address the new versions of the journal endpoints in 2.9.8 (even before I fixed the paging issue for you in 2.10.8) and RefId is no longer in there, along with "ExtraInfo" and the PartyType properties.

Please upgrade to 2.10.8

https://github.com/seraphx2/ESI.NET/releases

**Comment by mrurb** [comment]
Hmm that’s interesting, because I updated to the new version from nuget(2.10.8) and I’m using the new page logic that you put in, but what I posted above is what I get back after updating, I will have a further look at it tomorrow.

**Comment by seraphx2** [comment]
OK. Definitely interesting because I'm looking at both develop and master branches and the new class properties are definitely there.
