### ISSUE TITLE
Example ESI Url needs updating in documentation

### ISSUE THREAD

**Issue by chris-cheshire** [seraphx2/ESI.NET#19]
The latest url is now https://esi.evetech.net/

**Comment by chris-cheshire** [comment]
Happy to pull and fix this myself, great work by the way - very grateful that you have done this

**Comment by seraphx2** [comment]
Looks like Urban got it.
Thanks for pointing that out. Wasn't even thinking about the documentation when that changed.

And no problem. :)

**Comment by chris-cheshire** [comment]
No worries dude!
