### ISSUE TITLE
Error being thrown on  Type - Mass

### ISSUE THREAD

**Issue by Monkey7539** [seraphx2/ESI.NET#2]
Error being thrown by scientific notation Mass's at data pull.

**Comment by seraphx2** [comment]
Are you using the NuGet package? I changed it from decimal to double.
I believe that should most likely be able to hold the value.

**Comment by Monkey7539** [comment]
I was the nuget was set to decimal until little while ago. You may also want to update dogma attribute for type to double as some of them throw decimal error as well.

**Comment by seraphx2** [comment]
ok. will do when I get home.

Robert Burke | Gamer / Developer
Sent from Outlook<https://aka.ms/qtex0l> on my iPhone
________________________________

**Comment by Monkey7539** [comment]
np. I ended up cloning and using local copy for the time being. Just figured I'd help with debugging. I know it can be a pain.

**Comment by seraphx2** [comment]
unfortunately I can only validly test so many things anyway (especially things to do with alliances) and will have to rely on people to come across issues I can't dream of and report them.

thanks for the help.

Robert Burke | Gamer / Developer
Sent from Outlook<https://aka.ms/qtex0l> on my iPhone
________________________________

**Comment by seraphx2** [comment]
@Monkey7539 Can you be more specific about the dogma one? I'm not following which you mean.

**Comment by DeathZeppelin** [comment]
I am gonna guess he was refering to the DefaultValue property in the Attribute class. its the only decimal i saw in all of the dogma section.

**Comment by seraphx2** [comment]
Fixed. Will be released in the near future.
