### ISSUE TITLE
Http Authorization Header Duplicate Key

### ISSUE THREAD

**Issue by SebFerraro** [seraphx2/ESI.NET#28]
> An item with the same key has already been added.
> at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
>    at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
>    at System.Net.Http.Headers.HttpHeaders.AddHeaderToStore(String name, HeaderStoreItemInfo info)
>    at System.Net.Http.Headers.HttpHeaders.CreateAndAddHeaderToStore(String name)
>    at System.Net.Http.Headers.HttpHeaders.GetOrCreateHeaderInfo(String name, Boolean parseRawValues)
>    at System.Net.Http.Headers.HttpHeaders.SetParsedValue(String name, Object value)
>    at System.Net.Http.Headers.HttpRequestHeaders.set_Authorization(AuthenticationHeaderValue value)
>    at ESI.NET.EsiRequest.<Execute>d__1`1.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at ESI.NET.Logic.UniverseLogic.<Structure>d__23.MoveNext()

Error potentially occurring on line 35 of EsiRequest.cs

Suggestion for fix:

> if (client.DefaultRequestHeaders.Contains("Authorization"))
> {
>             client.DefaultRequestHeaders.Remove("Authorization");
> }
> client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);

**Comment by seraphx2** [comment]
hmmm, so looking at my code, I feel like I ran into this before, which is why this exists at the beginning of each Execute call: `client.DefaultRequestHeaders.Clear();`

There are only two possible existing headers that are set during Execute: `Authorization` and `If-None-Match`. Do you know if you are totally up to date on ESI.NET version?
