### ISSUE TITLE
What is "code" in your example?

### ISSUE THREAD

**Issue by KeithBarrows** [seraphx2/ESI.NET#29]
In your intro you show how to get a token.  Yet, in that last line, you do not explain or show what `code` consists of.  Not mentioned anywhere.  Trying to figure it out from the CCP docs and I have not yet twigged on what it should be.  Thanks.

**Comment by DanFraserUK** [comment]
You can see an example in my project that uses this, on this page, line 129:

https://github.com/DanFraserUK/EvEESITool/blob/master/EvEESIDownloadTool/Authenticator.cs

**Comment by seraphx2** [comment]
Or also, code is from the SSO callback. You should read up on OAuth and Eve SSO to understand that better. It's a standard OAuth mechanism so I would not outline it's usage here because if you understand that you should be able to understand the example to the Initial SSO section.

**Comment by KeithBarrows** [comment]
Gotcha!  Thanks to both of you.  Moving forward again.


[image: --]
Keith Barrows
[image: https://]about.me/kbarrows
<https://about.me/kbarrows?promo=email_sig>
*The truly free individual is free only to the extent of his own
self-mastery. While those who will not govern themselves are condemned to
find masters to govern over them.*  -- Socrates
