### ISSUE TITLE
long instead of int

### ISSUE THREAD

**Issue by Hazzel1337** [seraphx2/ESI.NET#64]
hello, your universe/names/ uses long, but the api wants int, could you maybe fix that ? :)

`        public async Task<EsiResponse<List<ResolvedInfo>>> Names(List<long> any_ids)
        {
            return await EsiRequest.Execute<List<ResolvedInfo>>(_client, _config, EsiRequest.RequestSecurity.Public, HttpMethod.Post, "/universe/names/", null, null, any_ids.ToArray());
        }`

but eve api wants  https://esi.evetech.net/ui/#/Universe/post_universe_names 

> post_universe_names_ids[
example: List [ 95465499, 30000142 ]
maxItems: 1000
minItems: 1
title: post_universe_names_ids
uniqueItems: true
ids array
integer($int32)
title: post_universe_names_id
id integer
]

**Comment by Hazzel1337** [comment]
thank you for the fix, your libary is awsome and helps me a lot <3

**Comment by seraphx2** [comment]
yup yup. no problem!
