### ISSUE TITLE
wallet transaction allows, page not id 

### ISSUE THREAD

**Issue by Hazzel1337** [seraphx2/ESI.NET#73]
Hello,

on the https://esi.evetech.net/ui/#/Wallet/get_characters_character_id_wallet_transactions, 
its says i can put in a long id from where i want to pull transactions, the end point returns only 2500 transaction, so i need to put in an id to find all transactions. you code only allows pages, which there is none in the documentation for this end point. could you maybe implement beeing able to send a id(long) with the request ?

**Comment by seraphx2** [comment]
@Hazzel1337 NuGet package has been updated.
