### ISSUE TITLE
UserInterface.Waypoint endpoint needs token

### ISSUE THREAD

**Issue by MrBramme** [seraphx2/ESI.NET#9]
When calling _client.UserInterface.Waypoint(#####) an error gets thrown due to no Token present. When comparing with the code for Wallet I noticed there's no token being passed on that call. It is an authorized call.

I've done a quick'n'dirty adjustment locally that injects the token and then everything works fine.
If I find the time to do it properly I'll do so asap and send a pull request.

**Comment by seraphx2** [comment]
looks like I missed all of user interface.

**Comment by MrBramme** [comment]
I've added a pull request to resolve the issue.
